CREATE TABLE People (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(200) NOT NULL,
    Phone NVARCHAR(50) NULL,
    Email NVARCHAR(200) NOT NULL,
    PhotoFileName NVARCHAR(500) NULL
);
